# Generated by Django 2.1.5 on 2019-03-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('date', '0002_auto_20190327_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='date',
            field=models.DateField(verbose_name='날짜'),
        ),
    ]
