# Generated by Django 2.1.7 on 2019-03-27 05:36

from django.db import migrations, models
import harusijak.storage_backends
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('align', models.CharField(choices=[('right', 'right'), ('center', 'center'), ('left', 'left')], default='left', max_length=9)),
                ('background', models.ImageField(blank=True, null=True, storage=harusijak.storage_backends.PoemMediaStorage(), upload_to='', verbose_name='배경지')),
                ('content', models.TextField(verbose_name='내용')),
                ('title', models.CharField(max_length=12, verbose_name='제목')),
                ('written_time', models.TimeField(auto_now_add=True, verbose_name='작성 시간')),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('displayed', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-written_date', '-written_time'],
            },
        ),
    ]
