# Generated by Django 2.1.7 on 2019-03-27 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('date', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='poem',
            name='written_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='date.Date', verbose_name='작성 날짜'),
        ),
        migrations.AddField(
            model_name='like',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.Poem'),
        ),
        migrations.AddField(
            model_name='like',
            name='poet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dislike',
            name='poem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poem.Poem'),
        ),
        migrations.AddField(
            model_name='dislike',
            name='poet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
