# Generated by Django 2.1.5 on 2019-01-22 04:43

from django.db import migrations, models
import harusijak.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poem',
            options={'ordering': ['-written_date', '-written_time']},
        ),
        migrations.AlterField(
            model_name='poem',
            name='background',
            field=models.ImageField(blank=True, null=True, storage=harusijak.storage_backends.PoemMediaStorage(), upload_to='', verbose_name='배경지'),
        ),
    ]
