# Generated by Django 2.1.5 on 2019-03-21 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0004_dislike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='subject',
        ),
        migrations.AddField(
            model_name='poem',
            name='align',
            field=models.CharField(choices=[('right', 'right'), ('center', 'center'), ('left', 'left')], default='left', max_length=9),
        ),
        migrations.AlterField(
            model_name='poem',
            name='content',
            field=models.TextField(verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='written_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='date.Date', verbose_name='작성 날짜'),
        ),
    ]
