# Generated by Django 2.1.5 on 2019-03-21 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(max_length=20, unique=True, verbose_name='주제')),
                ('guide_format', models.TextField(max_length=100, verbose_name='가이드 형식')),
                ('guide_type', models.CharField(choices=[('free', 'free'), ('reply', 'reply'), ('blank', 'blank'), ('constraint', 'constraint')], default='free', max_length=10, verbose_name='가이드 타입')),
            ],
        ),
    ]
