# Generated by Django 2.1.7 on 2019-04-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='guide_format',
            field=models.TextField(blank=True, null=True, verbose_name='가이드 형식'),
        ),
    ]
