# Generated by Django 2.1.7 on 2019-03-27 05:36

from django.conf import settings
from django.db import migrations, models
import harusijak.storage_backends


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('identifier', models.CharField(max_length=30, unique=True, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, storage=harusijak.storage_backends.PoetMediaStorage(), upload_to='')),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('recent_visited_date', models.DateTimeField(auto_now=True)),
                ('do_get_email', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('favorite_poems', models.ManyToManyField(blank=True, related_name='keeped_by', to='poem.Poem')),
                ('subscribing_to', models.ManyToManyField(blank=True, related_name='subscribed_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
