# Generated by Django 2.1.5 on 2019-01-22 04:43

from django.db import migrations, models
import harusijak.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('poet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poet',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=harusijak.storage_backends.PoetMediaStorage(), upload_to=''),
        ),
    ]
