# Generated by Django 2.1.5 on 2019-03-11 11:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poem', '0004_dislike'),
        ('poet', '0002_auto_20190122_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='poet',
            name='favorite_poems',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='poem.Poem'),
        ),
        migrations.AddField(
            model_name='poet',
            name='subscribing_to',
            field=models.ManyToManyField(blank=True, related_name='_poet_subscribing_to_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
