# Generated by Django 2.1.5 on 2019-03-21 06:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poet', '0003_auto_20190311_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poet',
            name='favorite_poems',
            field=models.ManyToManyField(blank=True, related_name='keeped_by', to='poem.Poem'),
        ),
        migrations.AlterField(
            model_name='poet',
            name='subscribing_to',
            field=models.ManyToManyField(blank=True, related_name='subscribed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
